### ISSUE TITLE
Can this repo works on IPC2023 domain?

### ISSUE THREAD

**Issue by Lhyshining** [minecraft-saar/autoplanbench#2]
Can this repo works on IPC2023 domain? I run this repo, but some error occurs.
'assert templates_with_wrong_args == [] and templates_with_wrong_number_args == [], f'Error: there are translations that went wrong.\n' \
AssertionError: Error: there are translations that went wrong.
Wrong number of args: ['rotate-first-pass', 'rotate-first-pass-end', 'rotate-second-pass']
Wrong variable names: ['rotate-first-pass', 'rotate-first-pass-end', 'rotate-second-pass']'

**Comment by kastein** [comment]
Hi, I’m sorry for the late reply! This error occurred because the LLM generated NL snippets that did not include all parameters e.g, all 8 parameters from the rotate-first-pass action. That can sometimes happen if the number of parameters of an action is high. We have just published a newer version of our code that considerably reduces this problem in general and the APB 2.0 dataset that includes different IPC domains (including Folding).
